# Generated by Django 3.0.8 on 2020-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=100)),
                ('shedule', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('details', models.TextField(max_length=100)),
            ],
        ),
    ]
