# Generated by Django 3.0.8 on 2020-11-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='MyResource',
        ),
    ]
